### ISSUE TITLE
BUG: "krew" feature installer not working

### ISSUE THREAD

**Issue by salami738** [dodevops/cloudcontrol#142]
Our config file is

```
version: "3"
services:
    cli:
        image: "ghcr.io/dodevops/cloudcontrol-azure:latest"
...
        environment:
            - "FEATURES=kubernetes terraform:1.7.5 helm:3.14.0 stern:1.28.0 fish kc kubectlnodeshell azcopy krew"
...
            - "USE_run=yes"
            - 'RUN_COMMANDS=source /terraform/cloudcontrol-template/christ_webshop/project_commands'
```

If we set up cloudcontrol with this configuration, “krew” will not be installed.
